# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build gh-pages

on:
  push:
    branches: [ master ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Setting git config
      run: |
        git config --global user.email "fasihahmadfakhri@gmail.com"
        git config --global user.name "Fasih Ahmad Fakhri"
    - name: Build CogniCue in /tmp/build
      run: |
        mkdir /tmp/build
        python build.py -o /tmp/build        
    - name: Checkout and clean gh-pages branch
      run: |
        git fetch --all
        git checkout gh-pages
        rm -rf *
    - name: Copying new build
      run: |
        cp -av /tmp/build/* .
    - name: Checking git status
      run: |
        git status
    - name: Commiting new changes
      run: |
        git add .
        git commit -m"[CogniCue] Auto Build"
        git status
    - name: Publishing new changes
      run: |
        git push origin HEAD  
